bluelist/urls.py
from django.conf.urls import patterns, include, url

from bluelist.views import homepage, prof_list_get, prof_request, terms, contactRequest, about
from user_profile.views import userForm, signup, signin, signout, registration, userFileUpload, userDeleteFile, editAccount, cancelSubscription, stripeWebHook, profilePreview
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', homepage),	
	url(r'^admin/', include(admin.site.urls)),
	url(r'^signup$', signup),
	url(r'^signin$', signin),
	url(r'^signout$', signout),
	url(r'^proflist$', prof_list_get),
	url(r'^profrequest$', prof_request),
    url(r'^registration$', registration),
    url(r'^userDeleteFile$', userDeleteFile),
    url(r'^userFileUpload$',userFileUpload),
    url(r'^editaccount$',editAccount),
    url(r'^cancelsubscription$',cancelSubscription),
    url(r'^userform$', userForm),
    url(r'^termsandconditions$', terms),  
    url(r'^stripeWebHook$', stripeWebHook),
    url(r'^contactrequest$', contactRequest),
    url(r'^profilepreview$', profilePreview),
    url(r'^about$', about)
)


from django.conf import settings

#This is used to serve static files in development

if settings.DEBUG:
     urlpatterns += patterns('',url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
     'document_root': settings.BASE_PATH+'/bluelist/media'}))
    
    

user_profile/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


import sys, time


import os
def get_upload_path(instance, filename):
    return os.path.join("profile_data","user_%d" % instance.user.pk, filename)


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email,
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
        db_index=True,
        error_messages={'unique' : 'This Email address is already in use',
                        'invalid' : 'This Email address is invalid',
                        'required': 'An Email address is required'},
    )
    
    
    is_active = models.BooleanField(default=True)
    is_registered = models.BooleanField(default=False)
    stripe_id=models.CharField(max_length=100,blank=True)
    
    is_admin = models.BooleanField(default=False)
    
    objects = UserManager()

    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    # On Python 3: def __str__(self):
    def __unicode__(self):
        return self.email
        
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
        



class CatManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class State(models.Model):
    objects=CatManager()
    
    name = models.CharField(max_length=30)
    
    def natural_key(self):
            return (self.name)
    
    def __unicode__(self):
        return self.name
	
class City(models.Model):
    objects=CatManager()
    
    name = models.CharField(max_length=30)
    state = models.ForeignKey(State)

    def natural_key(self):
            return (self.name)

    def __unicode__(self):
        return self.name
	
	
class SkillCategory(models.Model):
    objects=CatManager()
    
    name = models.CharField(max_length=30)
    
    def natural_key(self):
            return (self.name)
    
    def __unicode__(self):
        return self.name
	
class Skill(models.Model):
    objects=CatManager()
    
    name = models.CharField(max_length=30)
    skillcategory = models.ForeignKey(SkillCategory)
    
    def natural_key(self):
            return (self.name)
    
    def __unicode__(self):
        return self.name


class UserProfile(models.Model):
    
    user = models.OneToOneField(User)
    
    name = models.CharField(max_length=20)
    service = models.CharField(max_length=20)
    shortdesc= models.CharField(max_length=200)
    longdesc = models.CharField(blank=True, max_length=600)
    city = models.ForeignKey(City,null=True)
    state = models.ForeignKey(State,null=True)
    skillcategory = models.ForeignKey(SkillCategory,null=True)
    skill = models.ForeignKey(Skill,null=True)
    
    public_email=models.EmailField(blank=True)
    public_phone_num=models.CharField(blank=True,max_length=30)
    
    prof_pic = models.ImageField(upload_to=get_upload_path,blank=True)
    
    link1 = models.URLField(blank=True)
    link1_pic=models.ImageField(upload_to=get_upload_path,blank=True)
    link1_title = models.CharField(blank=True, max_length=50)
    link1_desc = models.CharField(blank=True, max_length=200)
    
    link2 = models.URLField(blank=True)
    link2_pic=models.ImageField(upload_to=get_upload_path,blank=True)
    link2_title = models.CharField(blank=True, max_length=50)
    link2_desc = models.CharField(blank=True, max_length=200)
    
    link3 = models.URLField(blank=True)
    link3_pic=models.ImageField(upload_to=get_upload_path,blank=True)
    link3_title = models.CharField(blank=True, max_length=50)
    link3_desc = models.CharField(blank=True, max_length=200)
    
    link4 = models.URLField(blank=True)
    link4_pic=models.ImageField(upload_to=get_upload_path,blank=True)
    link4_title = models.CharField(blank=True, max_length=50)
    link4_desc = models.CharField(blank=True, max_length=200)
    
    link5 = models.URLField(blank=True)
    link5_pic=models.ImageField(upload_to=get_upload_path,blank=True)
    link5_title = models.CharField(blank=True, max_length=50)
    link5_desc = models.CharField(blank=True, max_length=200)
    
    link6 = models.URLField(blank=True)
    link6_pic=models.ImageField(upload_to=get_upload_path,blank=True)
    link6_title = models.CharField(blank=True, max_length=50)
    link6_desc = models.CharField(blank=True, max_length=200)
    
    link7 = models.URLField(blank=True)
    link7_pic=models.ImageField(upload_to=get_upload_path,blank=True)
    link7_title = models.CharField(blank=True, max_length=50)
    link7_desc = models.CharField(blank=True, max_length=200)
    
    link8 = models.URLField(blank=True)
    link8_pic=models.ImageField(upload_to=get_upload_path,blank=True)
    link8_title = models.CharField(blank=True, max_length=50)
    link8_desc = models.CharField(blank=True, max_length=200)


    file1 = models.FileField(upload_to=get_upload_path,blank=True)
    file1_title = models.CharField(blank=True, max_length=50)
    file1_desc = models.CharField(blank=True, max_length=200)
    
    file2 = models.FileField(upload_to=get_upload_path,blank=True)
    file2_title = models.CharField(blank=True, max_length=50)
    file2_desc = models.CharField(blank=True, max_length=200)
    
    file3 = models.FileField(upload_to=get_upload_path,blank=True)
    file3_title = models.CharField(blank=True, max_length=50)
    file3_desc = models.CharField(blank=True, max_length=200)
    
    file4 = models.FileField(upload_to=get_upload_path,blank=True)
    file4_title = models.CharField(blank=True, max_length=50)
    file4_desc = models.CharField(blank=True, max_length=200)
    
    file5 = models.FileField(upload_to=get_upload_path,blank=True)
    file5_title = models.CharField(blank=True, max_length=50)
    file5_desc = models.CharField(blank=True, max_length=200)
    
    file6 = models.FileField(upload_to=get_upload_path,blank=True)
    file6_title = models.CharField(blank=True, max_length=50)
    file6_desc = models.CharField(blank=True, max_length=200)
    
    file7 = models.FileField(upload_to=get_upload_path,blank=True)
    file7_title = models.CharField(blank=True, max_length=50)
    file7_desc = models.CharField(blank=True, max_length=200)
    
    file8 = models.FileField(upload_to=get_upload_path,blank=True)
    file8_title = models.CharField(blank=True, max_length=50)
    file8_desc = models.CharField(blank=True, max_length=200)



    def __unicode__(self):
            return self.name

templates/about.html
<!DOCTYPE html>
<html>
<head>

<title> BlueList </title>


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-45738608-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


<script type="text/javascript"> 
	var signed_in = "{{user|safe}}";
	var registered = "{{registered|safe}}";
</script>



{% load staticfiles %}

<script type="text/javascript" src="{% static "jquery.js" %}" > </script>
<script type="text/javascript" src="{% static "header.js" %}" > </script>
<script>  $(document).ready(function(){
  
renderHeader(signed_in, registered); });</script>

<link rel="stylesheet" type="text/css" href="{% static "header.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "body.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "base.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "termsandconditions.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "about.css"%}">

</head>
<body>

	<div class= "body-container">
	
	{% include 'header.html' %}


		<div class="base-container">
			
			<h3 class="title">About Bluelist</h4>
			
			<div class="text-div">
			
			<p class="about-text">Bluelist was created to make talented local freelancers accessible to everyone.</p>
			
			<h4 class="header">Freelancers</h3>
			
			<p class="about-text">Freelancers can create a profile that explains the service they offer and provide references or examples of their work through links and uploaded files.</p>
			
			
			<h4 class="header">Looking for a Freelancer?</h3>

			<p class="about-text">On Bluelist you can easily find freelancers that are available in your city and then decide which ones to contact based on examples of their work. </p>
			
			
			</div>
			
			
		</div>
	
	
</body>
</html>

templates/edit_account.html
 <html>
<head>
    <title>Bluelist</title>


	{% load staticfiles %}
	
	
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-45738608-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
	<script type="text/javascript"> 
		var signed_in = "{{user|safe}}";
		var registered = "{{registered|safe}}";
	</script>

	
	<script type="text/javascript" src="{% static "jquery.js" %}" > </script>
	<script type="text/javascript" src="{% static "edit_account.js" %}" > </script>	
		<script type="text/javascript" src="{% static "header.js" %}" > </script>	
	<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
	
	
	<script type="text/javascript">
	  // This identifies your website in the createToken call below
	  Stripe.setPublishableKey('pk_test_OJ4HXQ3SBShYjtgqA6hq7Ynr');
	  // ...
	</script>
	
	<link rel="stylesheet" type="text/css" href="{% static "header.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "body.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "edit_account.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "base.css" %}">
	

</head>
<body>

	
 
<div class= "body-container">
<div class="body-scroll">

<div class="base-container">
<div class="form-container">
	
	
	<h3 class="title"> Edit Account </h3>
	
	
	
	<div id="content_container" class="content-container">
		<a class="button_tag" id="cancel_subscription">Cancel Subscription</a>

		<a class="button_tag" id="update_subscription" href="/registration">Update Credit Card</a>
		
		<p hidden class="text" id="cancel_message">Are you sure you want to cancel your membership?</p>
		<a class="button_tag" id="cancel_confirm" style="display:none">Yes</a>
		
	</div>

</div>
</div>
</div>
</div>


{% include 'header.html' %}

</body>
</html>

templates/header.html
<div class="navbar">
	<div class="logo">
		<a href="/"><p id="logo">BlueList</p></a>
	</div>
	
	
	<div class="menu-buttons">
	    <div class= "menu-div-nav" > 
        <ul id="nav">  
            <li id="about_li">
                <a id="about" href="/about">Learn More</a>
            </li>

            <li id="signin_li">
                <a id="signin" href="#">Login</a>
            </li>


            <li id="signup_li">
                <a id="signup" href="#">Sign Up</a>
            </li>

            	<li id="account_li"> 
                	<a id="account" href="#">Account &#x25BE</a>
                        <ul>
                             <li><a id="prof_btn" href="/userform"></a></li>
							 <li><a id="subs_btn" href="/editaccount">Edit Account</a></li>
                             <li class="last"><a id="signout_btn" href="/signout">Sign Out</a></li>
                        </ul>
                 </li>

			</ul>

           </div>

	</div>
</div>

templates/profile_list.html
{% for key, value in profiles.items %}

	{% if value.more == "true"%}
		<div class="profile-index profile-min" id="prof{{value.pk}}">
	{% else %}
		<div class="profile-index profile-exp" id="prof{{value.pk}}">
	{% endif %}	
						<div class="index-pic">
							<a href="{{value.prof_pic}}" ><img class="index_image" src="{{value.prof_pic}}" ></a>
	    				</div>
				 		<div class="index-text">
				 			    <div class="profile-name">
								    <p class="index-name">{{value.name}}</p>
								</div>
								<div class="profile-tag">
								    <p class="tag">{{value.service}} in {{value.city}}, {{value.state}}</p>
								</div>
								<div class="short-desc description" >
								    <p class="index-desc">{{value.shortdesc}}</p>
								</div>
								<div hidden class="exp_section">
								    <div class="long-desc description">
								        <p class="long-desc description">{{value.longdesc}}</p>
								    </div>
								    <div class="links">
								       
										{% for link in value.link_list %}
								
												<div class="link-container">
							                                    <div class="link-title-container">
							                                        <a href="{{link.url}}">{{link.title}}</a>
							                                    </div>
							                                    <div class="link-desc-container">
							                                        <p class="link-desc">{{link.desc}}</p>
							                                    </div>
							                     </div>
								
										{% endfor %}
										
										{% for file in value.file_list %}
								
												<div class="file-container">
							                                    <div class="file-title-container">
							                                        <a href="{{file.url}}">{{file.title}}</a>
							                                    </div>
							                                    <div class="file-desc-container">
							                                        <p class="file-desc">{{file.desc}}</p>
							                                    </div>
								    			</div>
								
										{% endfor %}
								
									</div>
							
								</div>
								
								<div class="index-options">
								    <div class="option">
										<a class="index-option" id="contact">Contact</a>
										
										{% if value.more == "true"%}
										<a class="index-option" id="more">More</a>
										<a hidden class="index-option" id="less">Less</a>
										{% endif %}
										
					 			    </div>
					 			</div>
					 	
					</div>

	</div>
{% endfor %}	
	
	
	

templates/user_form.html
<!DOCTYPE html>
<html>
<head>

<title> BlueList </title>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-45738608-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


	<script type="text/javascript"> 
		var states = {{statelist|safe}};
		var cities = {{citylist|safe}};
		var categories = {{catlist|safe}};
		var skills = {{skilllist|safe}};
		var signed_in = "{{user|safe}}";
		var registered = "{{registered|safe}}";
		var max_upload_size = {{max_upload_size|safe}};
	</script>

	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static "base.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "body.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "userform.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "header.css" %}">


	
	
	<script type="text/javascript" src="{% static "jquery.js" %}" > </script>
	<script type="text/javascript" src="{% static "userform.js" %}" > </script>
	<script type="text/javascript" src="{% static "authentication.js" %}" > </script>
	<script type="text/javascript" src="{% static "header.js" %}" > </script>
	


</head>
<body>
	

<div class= "body-container">
	
	{% include 'header.html' %}
	
<div class="base-container-userform">

    

	<form action="" method="post" enctype="multipart/form-data">
		{{ form.non_field_errors }}
		
	<div class="form-container">
			

			{% if form.errors %}
		        <p class="error-indicator">
		            Please correct the error{{ form.errors|pluralize }} below
		        </p>
		    {% endif %}
	

		<div class="label-div"><h4 class="form-label"> Name </h4> <p class="sub-label">(Required)</p></div>
		{{form.name.errors}}
		<div class="form-outer-field"><div class="form-field-container">{{form.name}}</div></div>
		
			<div class="split-form-container">
					<div class="split-form-div">
					
						 <div class="label-div"><h4 class="form-label"> Profile Picture </h4></div>
						{{form.prof_pic.errors}}
							
						
							<div class="form-outer-field-new">
								<div class="form-field-container">					
									
									<div class='file-error' id="prof_pic_file_error">
									</div>
									
									
									<div {% if pic_url == "" %} hidden {% endif %} id="prof_im_container1" class="form-field-container file_div">
									
										<div class="image_div">
											<a target="_blank" href="{{ pic_url|safe }}"><img id="img_prof_pic" src="{{ pic_url|safe }}" /></a>
											<div class="footerBar">	
												<a class="prof_pic_btn pic_replace" id="prof_pic_replace" href="#">Replace </a>
												<a class="prof_pic_btn pic_delete" id="prof_pic_delete" name="prof_pic" href="#">Delete </a>
                        					</div>
										</div>
											
											<input hidden id="id_prof_pic" name="prof_pic" type="file" />
											
										</div>
										
										<div {% if pic_url != "" %} hidden {% endif %} id="prof_im_container2" class="form-field-container file_div">
	                        				<input id="id_prof_pic" name="prof_pic" type="file" />
	                    				</div>
								</div>
							</div>
						
					</div>
				
					<div class="split-form-div">
						 <div class="cat-label-div">
										<h4 class="form-label"> Location</h4><p class="sub-label">(Required)</p>	
							</div>
						
						<div class="cat-div-container">		
									{{form.state.errors}}
								<div class="cat-container">
									<p class="cat-label">State</p>
										{{form.state}} 
								</div>
								
								
								{{form.city.errors}}
								<div class="cat-container">	
									<p class="cat-label">City</p>
										{{form.city}}  
								</div>
						 </div>
						
						
							<div class="cat-label-div">
								<h4 class="form-label">Service Type</h4><p class="sub-label">(Required)</p>
							</div>
								
							<div class="cat-div-container">		
								{{form.skillcategory.errors}}
									<div class="cat-container">
										<p class="cat-label">Category </p>
										{{form.skillcategory}}
									</div>
								{{form.skill.errors}}
									<div class="cat-container">		
									<p class="cat-label">Specialty </p> 
										{{form.skill}}
									</div>
							</div>

					</div>
				</div>
			
		
		
		<div class="label-div"><h4 class="form-label"> Service </h4> <p class="sub-label"> (Required)</p></div>
		{{form.service.errors}}
		<div class="form-outer-field"><div class="form-field-container">{{form.service}}</div></div>
		
		
		<div class="label-div">
			<h4 class="form-label"> Listing Description </h4> 
			<p class="sub-label">(Required)</p>  
			<p class="char-count" id='short_desc_num'></p>
			
			</div>
		{{form.shortdesc.errors}}
		<div class="form-outer-field"><div class="form-field-container">{{form.shortdesc}}</div></div>

		
			<div id="additional_info">
				<div class="label-div">
					<h4 id="add_info_label" class="form-label"> Additional Information </h4>
					<p class="char-count" id='long_desc_num'></p>	
				</div>
				{{form.longdesc.errors}}
				<div class="form-outer-field"><div class="form-field-container">{{form.longdesc}}</div></div>
			</div>
		


			<div class="label-div"><h4 id="contact_label" class="form-label"> Contact Information </h4>
			
			<p class="contact-message"> (Contact information will be available to signed in users only) </p>
			</div>
		
			
			<div id="contact" class="contact-container">
				{{form.public_email.errors}}
				
					<div class="form-outer-field"><div class="form-field-container">	
							
						<div class="sub-label-div"><p class="form-sub-label">Contact Email Address</p></div>
							{{form.public_email}}
						
					</div></div>
				
			
				{{form.public_phone_num.errors}}
				
					<div class="form-outer-field"><div class="form-field-container">	
								
							<div class="sub-label-div"><p class="form-sub-label">Contact Phone Number</p></div>
							{{form.public_phone_num}}
					</div></div>
			</div>
		
		
	<div class="label-div" id="links_label"><h4  class="form-label"> Profile Links </h4></div>
		
		
		{% for num in link_list %}
		<div id="link{{forloop.counter}}" class="link-container">
			
				<div class="form-outer-field"><div class="form-field-container">	
					{{num.link_error}}
					<div class="sub-label-div"><p class="form-sub-label">Link URL</p></div>
					
					<input id="id_link{{forloop.counter}}" maxlength="200" name="link{{forloop.counter}}" type="text" value="{{ num.link }}"/>
				
				</div></div>
			
			
				<div class="form-outer-field"><div class="form-field-container">	
						{{num.link_title_error}}
						<div class="sub-label-div"><p class="form-sub-label">Link Title</p></div>
						
						<input id="id_link{{forloop.counter}}_title" maxlength="50" name="link{{forloop.counter}}_title" type="text" value="{{num.link_title}}" />
					
				</div></div>
			
				<div class="form-outer-field"><div class="form-field-container">	
						{{num.link_desc_error}}
				<div class="sub-label-div"><p class="form-sub-label">Link Description</p><p class="char-count link-desc-char-num" id='link_desc_num{{forloop.counter}}'></p></div>
						
				<textarea cols="40" class="media-desc" id="id_link{{forloop.counter}}_desc" name="link{{forloop.counter}}_desc" rows="2">{{num.link_desc}}</textarea>
					
				</div></div>
			
		</div>
		{% endfor %}
		
		
		
		<div class="label-div" id="uploads_label"><h4 class="form-label"> Uploaded Files </h4></div>
		
		
		{% for num in file_list %}
		
		<div id="file{{forloop.counter}}" class="file-container">
		
		
			
			
				<div class="form-outer-field"><div class="form-field-container">	
				<div class="file-error" id="file{{forloop.counter}}_error">
				</div>
					
					
						<div {% if not num.file %} hidden {% endif %} id="file{{forloop.counter}}_container1" class="file_container file_div">
							<input hidden id="id_file{{forloop.counter}}" name="file{{forloop.counter}}" type="file" />

							<ul class="file_upload_list">
								<li class="file_upload_li"><a class="file file-view" id="view_file{{forloop.counter}}" href="{{num.file}}">View Current File</a></li>
								<li class="file_upload_li"><a class="file file-replace" id="replace_file{{forloop.counter}}" href="#">Replace</a></li>
								<li class="file_upload_li"><a class="file file-delete" name="file{{forloop.counter}}" id="delete_file{{forloop.counter}}" href="#">Delete</a></li>
							</ul>
						</div>
						
						<div {% if num.file %} hidden {% endif %} id="file{{forloop.counter}}_container2" class="file_div">
							<input id="id_file{{forloop.counter}}" name="file{{forloop.counter}}" type="file" />
						</div>
					
					
				
				</div></div>
			
		
			<div class="form-outer-field"><div class="form-field-container">	
				
					<div class="sub-label-div"><p class="form-sub-label">File Title</p></div>
					{{num.file_title_error}}</p>
					<input id="id_file{{forloop.counter}}_title" maxlength="50" name="file{{forloop.counter}}_title" type="text" value="{{num.file_title}}" />
				
			</div></div>
		

		
			<div class="form-outer-field"><div class="form-field-container">	
			{{num.file_desc_error}}
			<div class="sub-label-div"><p class="form-sub-label">File Description</p><p class="char-count link-desc-char-num" id='link_desc_num{{forloop.counter}}'></p></div>
			<textarea cols="40" class="media-desc" id="id_file{{forloop.counter}}_desc" name="file{{forloop.counter}}_desc" rows="2">{{num.file_desc}}</textarea>
			
			</div></div>
		
		
		</div>
	
		{% endfor %}
	
		
		
		<div class='form_button_container'>
			<div class='form_button_div'>
					<div class="add_ref" id="add_contact" >

						<p class="add_ref_text"> Add Contact </p>
					</div>
						<div class="add_ref" id="add_info" >
							<p class="add_ref_text"> Add Text </p>
						</div>
						<div class="add_ref" id="add_link" >
							<p class="add_ref_text"> Add a Link </p>
						</div>
						<div class="add_ref" id="add_file" >

							<p class="add_ref_text"> Upload a File </p>
						</div>
			</div>
			
			<div class="submit_button_div">
	        	<input id="submitButton" type="submit" value="Save Profile">
			</div>
	
		</div>
		
	</form>

</div>
</div>
</div>




</body>
</html>

templates/user_signin.html
<html>
<head>
    <title>User Signin</title>
</head>
<body>
	
	
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

		<form action="" method="post">
		        <table>
		            {{ form.as_table }}
		        </table>
		        {% csrf_token %}
		        <input type="submit" value="Submit">
		</form>

</body>
</html>